name: gh-pages

on:
    push:
        branches:
            - main
        paths:
            - "paper/**"
            - "**/gh-pages.yaml"
    workflow_dispatch:

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo apt -y update
                  sudo apt -y install --upgrade --no-install-recommends git python3 python3-pip
                  sudo -H pip3 install --upgrade bikeshed
                  sudo bikeshed update

            - name: Generate docs
              run: |
                  cd paper
                  bikeshed spec

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./paper
